# golangci-lint 配置文件
# 使用: golangci-lint run

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # 检查未处理的错误
    - gosimple      # 简化代码建议
    - govet         # Go 官方检查工具
    - ineffassign   # 检测无效赋值
    - staticcheck   # 静态分析
    - unused        # 未使用的代码
    - gofmt         # 格式检查
    - goimports     # import 检查
    - misspell      # 拼写检查
    - revive        # 代码质量
    
linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
  
  govet:
    enable-all: true
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false

issues:
  exclude-rules:
    # 排除测试文件的某些检查
    - path: _test\.go
      linters:
        - errcheck
    # 排除 Wire 生成的代码
    - path: wire_gen\.go
      linters:
        - all
  
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
