// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"gin_demo/internal/app"
	"gin_demo/internal/app/handler/health"
	"gin_demo/internal/app/handler/user"
	"gin_demo/internal/app/middleware"
	"gin_demo/internal/config"
	"gin_demo/internal/domain/service"
	"gin_demo/internal/repository"
)

// Injectors from wire.go:

// InitApp 初始化应用（Wire 会自动生成实现）
func InitApp(cfg *config.Config) (*app.Application, error) {
	db, err := provideDatabase(cfg)
	if err != nil {
		return nil, err
	}
	universalClient := provideRedis(cfg)
	manager := provideCacheManager(universalClient)
	userRepository := repository.NewUserRepository(db, manager)
	userService := service.NewUserService(userRepository)
	jwtManager := provideJWTManager(cfg)
	handler := user.NewHandler(userService, jwtManager)
	checker := provideHealthChecker(db, universalClient)
	healthHandler := health.NewHandler(checker)
	authMiddleware := middleware.NewAuthMiddleware(jwtManager)
	handlers := app.NewHandlers(handler, healthHandler, authMiddleware)
	taskManager := provideTaskManager(db, universalClient)
	application := app.New(cfg, db, universalClient, handlers, taskManager)
	return application, nil
}
