// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"database/sql"
)

type Querier interface {
	// 统计用户总数
	CountUsers(ctx context.Context) (int64, error)
	// 创建用户（MySQL 使用 execresult 获取 LastInsertId）
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	// 软删除用户（设置状态为禁用）
	DeleteUser(ctx context.Context, id int64) error
	// 通过 Email 获取用户（包含密码，用于登录验证）
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// 通过 ID 获取用户
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// 通过 Username 获取用户
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	// 通过 Email 获取用户 ID（用于缓存索引）
	GetUserIDByEmail(ctx context.Context, email string) (int64, error)
	// 通过 Username 获取用户 ID（用于缓存索引）
	GetUserIDByUsername(ctx context.Context, username string) (int64, error)
	// 列出用户（分页）
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	// 更新用户信息
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	// 更新用户密码
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
